projet/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  get '/accueil', to: 'event#accueil'
  get '/event', to: 'event#event'
  get '/all_event', to: 'event#all_event'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

projet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

projet/app/models/attendance.rb
class Attendance < ApplicationRecord
end

projet/app/models/event.rb
class Event < ApplicationRecord
  
end

projet/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

projet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

projet/app/controllers/event_controller.rb
class EventController < ApplicationController
  
  def index
  end

end

projet/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end

      before_action :authenticate_user!, only: [:secret]
  
  def after_create
  end


end

projet/app/helpers/application_helper.rb
module ApplicationHelper
end

projet/app/helpers/event_helper.rb
module EventHelper
end

projet/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

projet/app/views/event/accueil.html.erb
<center><h1><i>Bienvenue sur le site</i></h1>
<h2>Pour voir la liste des événements :</h2>
<a button type="button" href="/all_event" class="btn btn-outline-primary me-2">Clique ici</button></a>

projet/app/views/event/all_event.html.erb
<div class="row text-center">
      <!-- Team item-->
      <div class="col-xl-3 col-sm-4 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://pbs.twimg.com/media/DHfT1zSUIAARbz8.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Evénement 1</h5><span class="small text-uppercase text-muted">Texte</span>
          <ul class="social mb-0 list-inline mt-3">
          </ul>
        </div>
      </div>

      <div class="col-xl-3 col-sm-4 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://pbs.twimg.com/media/DHfT1zSUIAARbz8.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Evénement 2</h5><span class="small text-uppercase text-muted">Texte</span>
          <ul class="social mb-0 list-inline mt-3">
          </ul>
        </div>
      </div>

      <div class="col-xl-3 col-sm-4 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://pbs.twimg.com/media/DHfT1zSUIAARbz8.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Evénement 3</h5><span class="small text-uppercase text-muted">Texte</span>
          <ul class="social mb-0 list-inline mt-3">
          </ul>
        </div>
      </div>
      <!-- End-->

    </div>
  </div>

projet/app/views/event/event.html.erb
<center><h1><i>Crée ton événement</i></h1>

<form>
   
 <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Ton nom et prénom</label>
    </div>

        <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Nom de ton événemeent</label>
    </div>

        <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Date de ton événement</label>
    </div>

    <div class="form-floating col-5 m-3">
      <input type="last_name" class="form-control" id="floatingInput" placeholder="last_name">
      <label for="floatingInput">Décris-nous ce qu'il va se passer</label>
    </div>
    <div class="checkbox mb-3">
    </div>
    <button class="wbtn btn-lg btn-primary col-3 m-3" type="submit">Ajoute-le</button>
  </form></center>

projet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event World</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </head>

  <body>

  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="" class="nav-link px-2 link-blue">EVENT WORLD</a></li>
        <li><a href="/accueil" class="nav-link px-2 link-dark">Accueil</a></li>
        <li><a href="/event" class="nav-link px-2 link-dark">Crée ton événement</a></li>

      </ul>

      <div class="col-md-3 text-end">
        
        <%= link_to "Inscription", new_user_registration_path, class: "btn btn-outline-primary me-2"%>
        <%= link_to "Connexion", new_user_session_path, class: "btn btn-outline-primary me-2"%>
      </div>

    </header>
  </div>
    <%= yield %>
  </body>
</html>

projet/app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= button_to( "Log Out", destroy_user_session_path,  method: :delete) %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

projet/app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>